"""This module contains the cfg files of tasks generated by GPT."""

from .metacfg.saucemixsurprise import SaucemixsurpriseCfg

"""explicitly export the cfg files"""
__all__ = ["SaucemixsurpriseCfg"]
